config/routes.rb
Rails.application.routes.draw do
  get 'products/new'

  root 'static_pages#home'
  get 'addproduct' => 'products#new'  

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  VALID_EAN_REGEX = /\d{13}/
  validates :ean, presence: true, length: { maximum:13 },
                  format: { with: VALID_EAN_REGEX },
            uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end
  
  def edit
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.paginate(page:params[:page])
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class="container">

    <%= link_to "Products App", root_path, id:"logo" %>
    <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Products", products_path %></li>
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Products Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/products/edit.html.erb
<% provide(:title, "Edit Product") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |p| %>
      <%= render 'shared/error_messages' %>

      <%= p.label :name %>
      <%= p.text_field :name, class: 'form-control' %>

      <%= p.label :description %>
      <%= p.text_field :description, class: 'form-control' %>

      <%= p.label :ean %>
      <%= p.text_field :ean, class: 'form-control' %>

    
      <%= p.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/products/index.html.erb
<% provide(:title, 'All products') %>
<h1>All products</h1>
<%= will_paginate %>
<ul class="products">
  <% @products.each do |product| %>
    <li>
      
      <%= link_to product.name, product %>
    </li>
  <% end %>
</ul>

 <%= will_paginate %> 

app/views/products/new.html.erb
<% provide(:title, 'Add Product') %>
<h1>Add Product</h1>
<p>This is the form to create a new product</p>

app/views/products/show.html.erb
<%= @product.name %>, <%= @product.ean %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
<h1>Product Application</h1>
<p>This application presents a list of products</p>

<%= link_to "Add Product", addproduct_path, class: "btn btn-lg btn-primary" %>

</div>